services:
  # What to call the service hosting the site. Because there is only
  # one service, it is automatically set as the default service, which
  # does a few things
  #   1. Clones the git repository into the service container
  #   2. Exposes port 80 to the Tugboat HTTP proxy
  #   3. Routes requests to the preview URL to this service
  jekyll:
    image: tugboatqa/debian:latest

    # A set of commands to run while building this service
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        - apt-get update
        - apt-get install ruby-full
        - export PATH="$PATH:/root/.gem/ruby/2.5.0/bin"
        - gem install bundler --user

      build:
        # jekyll's command to build your static site
        - bundle install
        - bundle exec jekyll build

        # Link the document root to the expected path.
        - ln -snf "${TUGBOAT_ROOT}/_site" "${DOCROOT}"